apiVersion: apps/v1
kind: Deployment  
metadata:  
  name: interview1
  namespace: quiz
  labels:
    app: interview1
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: interview1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:  
      labels:  
        app: interview1
    spec:
      nodeSelector:
         "beta.kubernetes.io/os":  linux
      containers:  
      - name: interview1
        image: 'farzadjalali/quiz01:latest'
        - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: interview1
  namespace: quiz
  labels:
    app: interview1
spec: 
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector: 
    app: interview1

